Seperated EF Core Migration checks into seperate job as build/test to fix strange errors

diff --git a/.github/workflows/build_test_ci.yml b/.github/workflows/build_test_ci.yml
--- a/.github/workflows/build_test_ci.yml
+++ b/.github/workflows/build_test_ci.yml
@@ -27,6 +27,55 @@ on:
         value: ${{ jobs.buildtest.outputs.artifact_id }}
 
 jobs:
+  #This is run in a seperate job to ensure clean code and seperation between database checks and other dotnet checks,
+  #which before was cauing strange errors when run in the same job
+  validate-ef:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read #This is required for actions/checkout
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up .NET Core
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: '9.x'
+
+      - name: Install dotnet-ef tool
+        run: dotnet tool install --global dotnet-ef --version ${{ vars.DOTNET_EF_VERSION }}
+
+      - name: Restore with dotnet
+        run: dotnet restore ./src --verbosity normal
+
+      - name: Build with dotnet
+        run: dotnet build ./src --no-restore --configuration Release --verbosity normal
+
+      - name: Ensure no missing EF Migrations
+        run: |
+          MIGRATION_NAME="__AutoCheck"
+          MIGRATION_STARTUP="./src/MH.Capstone.WebApp"
+          MIGRATION_PROJ="./src/MH.Capstone.Domain"
+          MIGRATION_CONTEXT="ApplicationDbContext"
+          MIGRATIONS_FOLDER="./src/MH.Capstone.Domain/Migrations"
+          # Run the add migration command. Specify the startup project and context if needed.
+          dotnet ef migrations add $MIGRATION_NAME --no-build --configuration Release -p $MIGRATION_PROJ -s $MIGRATION_STARTUP -c $MIGRATION_CONTEXT
+          echo "Running migration file check on path: '${MIGRATIONS_FOLDER}/*_${MIGRATION_NAME}.cs' (excluding '*.Designer.cs')"
+
+          # Check if the generated file contains any operations (e.g., migrationBuilder.)
+          if grep -q "migrationBuilder\." ${MIGRATIONS_FOLDER}/*_${MIGRATION_NAME}.cs --exclude=*.Designer.cs; then
+              echo "⚠️ Uncommitted model changes detected. A migration file is missing."
+              # Clean up the temporary file
+              dotnet ef migrations remove --no-build --configuration Release -p $MIGRATION_PROJ -s $MIGRATION_STARTUP -c $MIGRATION_CONTEXT
+              exit 1 # Fail the pipeline
+          else
+              echo "✅ Your model matches the last migration snapshot. No missing migrations."
+              # Clean up the temporary file
+              dotnet ef migrations remove --no-build --configuration Release -p $MIGRATION_PROJ -s $MIGRATION_STARTUP -c $MIGRATION_CONTEXT
+          fi
+
+          # Restore all modified files from EF Core check, including new, untracked files (clean)
+          git restore . && git clean -fd
+  
   buildtest:
     runs-on: ubuntu-latest
     permissions:
@@ -53,32 +102,6 @@ jobs:
 
       - name: Restore with dotnet
         run: dotnet restore ./src --verbosity normal
-
-      - name: Ensure no missing EF Migrations
-        run: |
-          MIGRATION_NAME="__AutoCheck"
-          MIGRATION_STARTUP="./src/MH.Capstone.WebApp"
-          MIGRATION_PROJ="./src/MH.Capstone.Domain"
-          MIGRATION_CONTEXT="ApplicationDbContext"
-          MIGRATIONS_FOLDER="./src/MH.Capstone.Domain/Migrations"
-          # Run the add migration command. Specify the startup project and context if needed.
-          dotnet ef migrations add $MIGRATION_NAME --configuration Release -p $MIGRATION_PROJ -s $MIGRATION_STARTUP -c $MIGRATION_CONTEXT
-          echo "Running migration file check on path: '${MIGRATIONS_FOLDER}/*_${MIGRATION_NAME}.cs' (excluding '*.Designer.cs')"
-
-          # Check if the generated file contains any operations (e.g., migrationBuilder.)
-          if grep -q "migrationBuilder\." ${MIGRATIONS_FOLDER}/*_${MIGRATION_NAME}.cs --exclude=*.Designer.cs; then
-              echo "⚠️ Uncommitted model changes detected. A migration file is missing."
-              # Clean up the temporary file
-              dotnet ef migrations remove --no-build --configuration Release -p $MIGRATION_PROJ -s $MIGRATION_STARTUP -c $MIGRATION_CONTEXT
-              exit 1 # Fail the pipeline
-          else
-              echo "✅ Your model matches the last migration snapshot. No missing migrations."
-              # Clean up the temporary file
-              dotnet ef migrations remove --no-build --configuration Release -p $MIGRATION_PROJ -s $MIGRATION_STARTUP -c $MIGRATION_CONTEXT
-          fi
-
-          # Restore all modified files from EF Core check, including new, untracked files (clean)
-          git restore . && git clean -fd
 
       - name: Build with dotnet
         run: dotnet build ./src --no-restore --configuration Release --verbosity normal -p:Version=${{ steps.release_version.outputs.version }}
